blank_issues_enabled: true
contact_links:
  - name: 📚 Nuxt API Party Documentation
    url: https://github.com/johannschopplich/nuxt-api-party#readme
    about: Check the documentation for usage of Nuxt API Party
